### ISSUE TITLE
Error after update

### ISSUE THREAD

**Issue by coolcom** [pdlove/homebridge-smartthings#43]
I did an $npm -g update homebridge-smartthings and now...

```
====================
ERROR LOADING PLUGIN homebridge-smartthings:
SyntaxError: Unexpected token (
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Plugin.load (/usr/lib/node_modules/homebridge/lib/plugin.js:65:22)
    at Server.<anonymous> (/usr/lib/node_modules/homebridge/lib/server.js:70:14)
    at Array.forEach (native)
    at Server._loadPlugins (/usr/lib/node_modules/homebridge/lib/server.js:66:22)
====================
No plugins found. See the README for information on installing plugins.
Loaded config.json with 0 accessories and 1 platforms.
---
Loading 1 platforms...
Error: The requested platform 'homebridge-smartthings.SmartThings' was not registered by any plugin.
    at API.platform (/usr/lib/node_modules/homebridge/lib/api.js:94:13)
    at Server._loadPlatforms (/usr/lib/node_modules/homebridge/lib/server.js:194:45)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:35:36)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:23:16)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)

```

**Comment by pdlove** [comment]
Is anyone else getting this? I uninstalled mine and re-installed it via npm and verified I'm definitely using the version I released and I'm not having this problem.

**Comment by coolcom** [comment]
Ok I can uninstall and reinstall and let you know.

**Comment by coolcom** [comment]
I believe it has something to do with my config.json.

**Comment by coolcom** [comment]
/usr/lib/node_modules/homebridge-smartthings/index.js:107
    addAttributeUsage(attribute, deviceid, mycharacteristic) {

I am going to completely reinstall my server and try everything from scratch

**Comment by coolcom** [comment]
Reinstalled everything from scratch (OS, etc.)

still getting:

```
/usr/lib/node_modules/homebridge-smartthings/index.js:107
    addAttributeUsage(attribute, deviceid, mycharacteristic) {
                     ^
====================
ERROR LOADING PLUGIN homebridge-smartthings:
SyntaxError: Unexpected token (
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Plugin.load (/usr/lib/node_modules/homebridge/lib/plugin.js:65:22)
    at Server.<anonymous> (/usr/lib/node_modules/homebridge/lib/server.js:70:14)
    at Array.forEach (native)
    at Server._loadPlugins (/usr/lib/node_modules/homebridge/lib/server.js:66:22)
====================
No plugins found. See the README for information on installing plugins.
Loaded config.json with 0 accessories and 1 platforms.
---
Loading 1 platforms...
Error: The requested platform 'homebridge-smartthings.SmartThings' was not registered by any plugin.
    at API.platform (/usr/lib/node_modules/homebridge/lib/api.js:94:13)
    at Server._loadPlatforms (/usr/lib/node_modules/homebridge/lib/server.js:194:45)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:35:36)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:23:16)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)

```

**Comment by coolcom** [comment]
This is my config.json:

```
andy@homebridge:~$ cat .homebridge/config.json
{
    "bridge": {
        "name": "Homebridge",
        "username": "my:mac:address",
        "port": 51826,
        "pin": "123-45-678"
    },

        "platforms": [
        {
                "platform": "homebridge-smartthings.SmartThings",
                "name": "SmartThings",
                "app_url": "https://graph.api.smartthings.com:443/api/smartapps/installations/",
                "app_id": "id-from-smartapp",
                "access_token": "token-from-smartapp",
                "polling_seconds": 3600,
                "update_seconds": 1
        }
                        ]
}
```

**Comment by pdlove** [comment]
Nothing looks out of whack. What version node are you using? The area indicated looks right and is working flawlessly everywhere I've looked.

**Comment by coolcom** [comment]
```
 nodejs                   0.10.25~dfsg2-2ub amd64             evented I/O for V8 javascript
ii  nodejs-dev               0.10.25~dfsg2-2ub amd64             evented I/O for V8 javascript (development files)
ii  nodejs-legacy            0.10.25~dfsg2-2ub all               evented I/O for V8 javascript (legacy symlink)
ii  npm                      1.4.21+ds-2     
```

is that what youre looking for?

**Comment by kdanthony** [comment]
Same issue here after upgrade:

$ nodejs -v
v0.10.42

**Comment by coolcom** [comment]
I think the problem is that we need to be on node v5.x

https://github.com/nfarina/homebridge/issues/347

I could not get the solutions posted on that to work, so I am yet again
starting from scratch.

**Comment by kdanthony** [comment]
Upgrading to 5.6.0 and then removing and reinstalling homebridge and homebridge-smartthings via npm solved the issue for me.

**Comment by coolcom** [comment]
how do you upgrade to 5.6 and what not?

**Comment by kdanthony** [comment]
Im using Ubuntu 14.04 LTS so not sure if that will apply for you but I did the following:

- Remove homebridge and homebridge-smartthings (you may need to remove others here if you are using different plugins): `sudo npm remove homebridge homebridge-smartthings -g`
- Install the Node repo for 5.x from nodesource: `curl -sL https://deb.nodesource.com/setup_5.x | sudo -E bash -`
- Upgrade nodejs: `sudo apt-get install -y nodejs`
- Verify I had node 5.6.0 after: `nodejs -v`
- Upgraded NPM to newest: `sudo npm install npm@latest -g`
- Install homebridge and homebridge-smartthings again via NPM: `sudo npm install homebridge homebridge-smartthings -g`

Things started up fine after that. My homebridge config was untouched by this but you may want to back it up anyway before starting.

**Comment by pdlove** [comment]
I'm running nodejs 0.10.29 without problems.

**Comment by coolcom** [comment]
Thank you very much for the detailed help! It is working for me now (sorta).

Homebridge starts and it loads all the smartthings, but I can't add it to my homekit. I think this is for me to figure out and not pdlove.

**Comment by kdanthony** [comment]
Remove/move the persist directory in your homebridge config dir if you are trying to readd it to homekit and it doesnt show up.

**Comment by coolcom** [comment]
Thank you!! Worked like a charm.

**Comment by coolcom** [comment]
And @pdlove, like you said it is FAST. You are awesome.

**Comment by pdlove** [comment]
No problem. I need to do work to speed up the Wink platform like this next weekend. Then I'll finally be able to work on a better app for the phone. :)

**Comment by mshah7** [comment]
Hi I have the same problem, followed the steps mentioned by kdanthony

nodejs -v
v0.6.19

I get the following error

[Sat Mar 12 2016 07:22:34 GMT+0000 (UTC)] ====================
[Sat Mar 12 2016 07:22:34 GMT+0000 (UTC)] ERROR LOADING PLUGIN homebridge-smartthings:
[Sat Mar 12 2016 07:22:34 GMT+0000 (UTC)] /usr/local/lib/node_modules/homebridge-smartthings/index.js:109
    addAttributeUsage(attribute, deviceid, mycharacteristic) {
                     ^
SyntaxError: Unexpected token (
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Plugin.load (/usr/local/lib/node_modules/homebridge/lib/plugin.js:65:22)
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:112:14)
    at Array.forEach (native)
    at Server._loadPlugins (/usr/local/lib/node_modules/homebridge/lib/server.js:108:22)
    at new Server (/usr/local/lib/node_modules/homebridge/lib/server.js:43:24)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:26:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
[Sat Mar 12 2016 07:22:34 GMT+0000 (UTC)] ====================
